### ISSUE TITLE
Inline `<code>` text breaks in awkward places

### ISSUE THREAD

**Issue by stormwarning** [stormwarning/typeset.css#23]
Possibly related to `word-break` property in measure mixin, or `white-space` property.

**Comment by techtolentino** [comment]
I'd be happy to take a look and possibly submit a PR.

Can you list examples of where this breaks? Looking at the page, it _seems_ fine, but not sure exactly where you're noticing it.

**Comment by stormwarning** [comment]
I think this may have been something to do with my demo site's styles interfering—I've probably fixed it, but I left the issue open as a reminder to double-check ;)

Thanks for taking a look!
