### ISSUE TITLE
Don't use recursive packaging

### ISSUE THREAD

**Issue by ChALkeR** [stormwarning/typeset.css#24]
_Disclaimer: I am not a user of this package, this was found during automated package downloading._

As of version _0.5.14_, your current npm package size is **80 MiB**, and your npm package installed size is **541 MiB**.

Your `_source` directory contains a previous version of `typeset.js`.
That version has a `_source` directory that contains a previous version of `typeset.js`.
That version has a `_source` directory that contains a previous version of `typeset.js`.

Each of those separately bundles `node_modules`: `gulp-sass`, `node-sass` (several of those), `gulp`, `autoprefixer`, etc, with all their deps.

```
541M    typeset.css-0.5.14.tgz
403M    typeset.css-0.5.14.tgz/_source/node_modules/typeset.css
248M    typeset.css-0.5.14.tgz/_source/node_modules/typeset.css/_source/node_modules/typeset.css
92M     typeset.css-0.5.14.tgz/_source/node_modules/typeset.css/_source/node_modules/typeset.css/_source/node_modules/typeset.css
```

This looks like a packaging bug that should be fixed.

**Comment by stormwarning** [comment]
Thanks for the heads-up; this should be fixed now.
